name: 'Build Debian package'
description: 'Build a Debian package'
inputs:
  distro:
    description: 'Docker image to build with'
    required: true
  sources:
    description: Any extra sources to add to apt
    required: false
    default: ''
  ppa:
    description: "An extra PPA to add to apt (no ppa: prefix)"
    required: false
    default: ''
  args:
    description: Arguments to pass to dpkg-buildpackage
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
